"""
Strict paper-backed composite alpha construction.

Default feature construction is intentionally conservative: only factors with
an explicit formula, a declared paper source, and satisfied input fields are
included in the directional alpha bank. Labels, gates, and diagnostics remain
available by explicit selection, but they are not silently mixed into the
default composite.
"""

from dataclasses import dataclass
import numpy as np
import pandas as pd
from typing import Optional

from .ofi      import mlofi, aggregated_ofi, trade_imbalance
from .features import (
    queue_imbalance,
)
from .auction  import auction_signal_series
from .advanced import (
    herding_intensity,
    aggressive_passive_imbalance,
    order_execution_imbalance,
    vpin,
    kyle_lambda,
    cancel_spike_imbalance,
)


@dataclass(frozen=True)
class FactorSpec:
    paper: str
    formula_id: str
    required_columns: tuple[str, ...]
    output_role: str
    strict_supported: bool
    alternative_required_columns: tuple[tuple[str, ...], ...] = ()
    # Provenance: who wrote the implementation
    #   "ours"              — implemented by us from scratch (HFT signals, current default)
    #   "crosssection"      — adapted from OpenSourceAP/CrossSection Python code
    #   "evolved"           — generated by Phase 2 evolution system (no direct paper)
    origin: str = "ours"
    # For evolved factors: comma-separated parent factor names
    parent_factors: str = ""


ORDER_EVENT_COLUMNS = (
    "limit_buy_vol",
    "limit_sell_vol",
    "cancel_buy_vol",
    "cancel_sell_vol",
    "market_buy_vol",
    "market_sell_vol",
)


FACTOR_REGISTRY: dict[str, FactorSpec] = {
    "mlofi": FactorSpec(
        paper="Stochastic Price Dynamics in Response to Order Flow Imbalance",
        formula_id="OFI state-transition formula, multi-level extension",
        required_columns=("bid_px_1", "bid_vol_1", "ask_px_1", "ask_vol_1"),
        output_role="alpha",
        strict_supported=True,
    ),
    "agg_ofi": FactorSpec(
        paper="Stochastic Price Dynamics in Response to Order Flow Imbalance",
        formula_id="rolling aggregation of paper OFI increments",
        required_columns=("bid_px_1", "bid_vol_1", "ask_px_1", "ask_vol_1"),
        output_role="alpha",
        strict_supported=True,
    ),
    "trade_imbalance": FactorSpec(
        paper="Trading Imbalance in Chinese Stock Market--A High-Frequency View",
        formula_id="polarity=(NOB-NOS)/(NOB+NOS)",
        required_columns=("cum_buy_count", "cum_sell_count"),
        alternative_required_columns=(
            ("buy_count", "sell_count"),
            # Volume fallback: not paper-exact NOB/NOS, but enables trade_imbalance
            # on Wind L2 3-second bars when per-transaction counts are unavailable.
            ("cum_buy_vol", "cum_sell_vol"),
        ),
        output_role="alpha",
        strict_supported=True,
    ),
    "api": FactorSpec(
        paper="Zhao, Sun, Wang (2025) High Frequency Liquidity in the Chinese Stock Market",
        formula_id="(M_buy+M_sell+C_buy+C_sell-L_buy-L_sell)/D̃ — spread-pressure gate (Zhao 2025)",
        required_columns=ORDER_EVENT_COLUMNS + ("bid_vol_1", "ask_vol_1"),
        output_role="gate",
        strict_supported=False,
    ),
    "oei": FactorSpec(
        paper="Cont, Kukanov, Stoikov (2014) depth-normalized OFI "
              "[Chi 2021 OEI requires per-order execution duration, uncomputable from LOB snapshots]",
        formula_id="((Lb-Cb-Ms)/Db)-((Ls-Cs-Mb)/Ds)",
        required_columns=ORDER_EVENT_COLUMNS + ("bid_depth", "ask_depth"),
        alternative_required_columns=(
            ("limit_buy_vol", "limit_sell_vol", "market_buy_vol", "market_sell_vol",
             "bid_px_1", "bid_vol_1", "ask_px_1", "ask_vol_1"),
        ),
        output_role="diagnostic",
        strict_supported=False,
    ),
    "vpin": FactorSpec(
        paper="Flow Toxicity and Liquidity in a High-frequency World",
        formula_id="BVC equal-volume bucket VPIN",
        required_columns=("last_price", "last_volume"),
        output_role="gate",
        strict_supported=True,
    ),
    "kyle_lambda": FactorSpec(
        paper="Kyle 1985 / tick-level price-impact literature",
        formula_id="lambda=Cov(delta_mid,signed_flow)/Var(signed_flow)",
        required_columns=("bid_px_1", "ask_px_1", "cum_buy_vol", "cum_sell_vol"),
        alternative_required_columns=(("bid_px_1", "ask_px_1", "market_buy_vol", "market_sell_vol"),),
        output_role="gate",
        strict_supported=True,
    ),
    "queue_imbalance": FactorSpec(
        paper="standing-book imbalance diagnostic, not a Caitong strict alpha",
        formula_id="(bid_size-ask_size)/(bid_size+ask_size)",
        required_columns=("bid_vol_1", "ask_vol_1"),
        output_role="diagnostic",
        strict_supported=False,
    ),
    "herding": FactorSpec(
        paper="herding literature requires cross-sectional/investor-group construction",
        formula_id="single-name LSV-style diagnostic only",
        required_columns=("cum_buy_count", "cum_sell_count"),
        alternative_required_columns=(("buy_count", "sell_count"),),
        output_role="diagnostic",
        strict_supported=False,
    ),
    "cancel_spike": FactorSpec(
        paper="spoofing/cancellation literature; full spoof detector not implemented",
        formula_id="explicit one-sided cancel burst diagnostic",
        required_columns=("cancel_buy_vol", "cancel_sell_vol"),
        output_role="diagnostic",
        strict_supported=False,
    ),
    "auction_signal": FactorSpec(
        paper="Empirical regularities of opening call auction",
        formula_id="auction imbalance scalar projection diagnostic",
        required_columns=(),
        output_role="diagnostic",
        strict_supported=False,
    ),
    "price_limit": FactorSpec(
        paper="Statistical Properties and Pre-Hit Dynamics of Price Limit Hits",
        formula_id="limit-hit state label",
        required_columns=("bid_px_1", "ask_px_1"),
        output_role="label",
        strict_supported=False,
    ),
}


DEFAULT_WEIGHTS = {
    "trade_imbalance": 0.25,
    "mlofi":           0.40,
    "agg_ofi":         0.35,
}


# ---------------------------------------------------------------------------
# Modular factor selection
# ---------------------------------------------------------------------------
# Pass factors=["flow", "auction"] (group names), factors=["mlofi", "api"]
# (factor names), or a mix, to build_feature_matrix. None = strict alpha only.

FACTOR_GROUPS: dict[str, list[str]] = {
    "alpha":       ["mlofi", "agg_ofi", "trade_imbalance"],
    "flow":        ["mlofi", "agg_ofi", "trade_imbalance"],
    "book":        ["queue_imbalance"],
    "behavior":    ["herding"],
    "auction":     ["auction_signal"],
    "limit":       ["price_limit"],
    "interaction": ["cancel_spike"],
    "gate":        ["vpin", "kyle_lambda"],
    "diagnostic":  ["queue_imbalance", "herding", "cancel_spike", "auction_signal"],
    "label":       ["price_limit"],
}

ALL_FACTORS: set[str] = set(FACTOR_REGISTRY)


def missing_required_columns(lob_df: pd.DataFrame, factor: str) -> list[str]:
    """Return missing columns for a registered factor, honoring alternatives."""
    spec = FACTOR_REGISTRY[factor]
    required_sets = (spec.required_columns,) + spec.alternative_required_columns
    if not required_sets:
        return []
    missing_by_set = [
        [col for col in required if col not in lob_df.columns]
        for required in required_sets
    ]
    if any(len(missing) == 0 for missing in missing_by_set):
        return []
    return missing_by_set[0]


def factor_available(lob_df: pd.DataFrame, factor: str) -> bool:
    return not missing_required_columns(lob_df, factor)


def _has_lob_levels(lob_df: pd.DataFrame, n_levels: int) -> bool:
    for lv in range(1, n_levels + 1):
        needed = (f"bid_px_{lv}", f"bid_vol_{lv}", f"ask_px_{lv}", f"ask_vol_{lv}")
        if any(col not in lob_df.columns for col in needed):
            return False
    return True


def expand_factor_selection(factors) -> Optional[set[str]]:
    """
    Expand a mixed list of group names / factor names into a factor set.
    None passes through (= all factors). Unknown names raise ValueError.
    """
    if factors is None:
        return None
    out: set[str] = set()
    for f in factors:
        if f in FACTOR_GROUPS:
            out.update(FACTOR_GROUPS[f])
        elif f in ALL_FACTORS:
            out.add(f)
        else:
            raise ValueError(
                f"Unknown factor or group '{f}'. "
                f"Groups: {sorted(FACTOR_GROUPS)}; factors: {sorted(ALL_FACTORS)}"
            )
    return out


def _default_factor_selection(lob_df: pd.DataFrame) -> set[str]:
    """Strict directional alpha factors whose declared fields are present."""
    return {
        name
        for name, spec in FACTOR_REGISTRY.items()
        if spec.output_role == "alpha"
        and spec.strict_supported
        and factor_available(lob_df, name)
    }


def build_feature_matrix(
    lob_df: pd.DataFrame,
    auction_value: Optional[float] = None,
    ofi_levels: int = 5,
    ofi_window: int = 10,
    qi_levels:  int = 1,
    half_life_auction_min: float = 20.0,
    prev_close: Optional[float] = None,
    instrument: str = "futures",
    herding_window: int = 20,
    factors=None,
    cancel_fallback: bool = False,
) -> pd.DataFrame:
    """
    Compute features from a LOB snapshot DataFrame.

    Parameters
    ----------
    lob_df           : output of simulate_lob_day() or real L2 loader
    auction_value    : scalar from auction.auction_imbalance(); None = skip
    ofi_levels       : LOB depth levels for OFI (max 10)
    ofi_window       : rolling ticks for aggregated_ofi / API / OEI
    qi_levels        : LOB depth levels for queue_imbalance
    half_life_auction_min : deprecated; auction projection ignores decay
    prev_close       : previous close; enables explicit price_limit label
    instrument       : "futures" or "stock"; enables explicit stock labels
    herding_window   : rolling ticks for intraday herding intensity
    factors          : modular strategy selection — list of group names
                       (see FACTOR_GROUPS) and/or factor names; None =
                       strict-supported directional alpha with present fields.
                       Optional factors still require their inputs (e.g.
                       "auction_signal" needs auction_value).
    cancel_fallback  : when True, oei and cancel_spike estimate cancel volumes
                       from LOB depth changes when explicit cancel columns are
                       absent. Useful for Wind L2 3-second snapshot data.
                       Not the paper-exact formula for those signals.
    """
    from .features import price_limit_signal

    explicit_selection = factors is not None
    selected = expand_factor_selection(factors)
    if selected is None:
        selected = _default_factor_selection(lob_df)

    def want(name: str) -> bool:
        return name in selected

    def ensure_available(name: str) -> bool:
        missing = missing_required_columns(lob_df, name)
        if missing:
            if explicit_selection:
                raise ValueError(
                    f"Factor '{name}' requires columns {FACTOR_REGISTRY[name].required_columns}; "
                    f"missing: {missing}"
                )
            return False
        return True

    feats: dict[str, pd.Series] = {}

    # --- base LOB / flow signals ---
    if want("mlofi") and ensure_available("mlofi"):
        if not _has_lob_levels(lob_df, ofi_levels):
            if explicit_selection:
                raise ValueError(f"mlofi requires bid/ask price and volume columns through level {ofi_levels}")
        else:
            feats["mlofi"] = mlofi(lob_df, n_levels=ofi_levels)
    if want("agg_ofi") and ensure_available("agg_ofi"):
        if not _has_lob_levels(lob_df, ofi_levels):
            if explicit_selection:
                raise ValueError(f"agg_ofi requires bid/ask price and volume columns through level {ofi_levels}")
        else:
            feats["agg_ofi"] = aggregated_ofi(lob_df, window=ofi_window, n_levels=ofi_levels)
    if want("trade_imbalance") and ensure_available("trade_imbalance"):
        feats["trade_imbalance"] = trade_imbalance(lob_df, window=ofi_window)
    if want("queue_imbalance") and ensure_available("queue_imbalance"):
        if not _has_lob_levels(lob_df, qi_levels):
            if explicit_selection:
                raise ValueError(f"queue_imbalance requires bid/ask volume columns through level {qi_levels}")
        else:
            feats["queue_imbalance"] = queue_imbalance(lob_df, n_levels=qi_levels)

    # --- strict event alpha ---
    if want("api") and ensure_available("api"):
        feats["api"] = aggressive_passive_imbalance(lob_df, window=ofi_window)
    if want("oei") and ensure_available("oei"):
        feats["oei"] = order_execution_imbalance(lob_df, window=ofi_window,
                                                  cancel_fallback=cancel_fallback)

    # --- explicit diagnostics / gates / labels ---
    if want("herding") and ensure_available("herding"):
        feats["herding"] = herding_intensity(lob_df, window=herding_window)
    if want("cancel_spike") and ensure_available("cancel_spike"):
        feats["cancel_spike"] = cancel_spike_imbalance(lob_df, window=ofi_window,
                                                        cancel_fallback=cancel_fallback)
    if want("vpin") and ensure_available("vpin"):
        feats["vpin"] = vpin(lob_df)
    if want("kyle_lambda") and ensure_available("kyle_lambda"):
        feats["kyle_lambda"] = kyle_lambda(lob_df)

    # --- optional priors / regime-specific labels ---
    if auction_value is not None and want("auction_signal"):
        feats["auction_signal"] = auction_signal_series(
            lob_df, auction_value, half_life_min=half_life_auction_min
        )

    if instrument == "stock" and prev_close is not None:
        if want("price_limit") and ensure_available("price_limit"):
            feats["price_limit"] = price_limit_signal(lob_df, prev_close)

    if not feats:
        raise ValueError(
            "Factor selection produced an empty feature set. Under strict "
            "mode this usually means the requested factors are diagnostics "
            "without their optional inputs, or the data is missing required "
            "paper-formula columns."
        )

    return pd.DataFrame(feats, index=lob_df.index)


def build_composite_alpha(
    feature_df: pd.DataFrame,
    weights: Optional[dict[str, float]] = None,
    clip_z: float = 4.0,
    norm_window: int = 200,
) -> pd.Series:
    """
    Combine features into a single composite alpha.

    Each feature is independently z-scored before weighting to
    equalise variance across signals. The final output is also
    z-scored so downstream threshold logic is scale-invariant.

    Only strict directional alpha columns with non-zero weights contribute.
    Gates, labels, and diagnostics may be present in `feature_df`, but are
    ignored by the composite unless the caller explicitly supplies weights.

    Parameters
    ----------
    feature_df  : output of build_feature_matrix
    weights     : override default weights (partial OK)
    clip_z      : clip individual features at ±clip_z before combining
    norm_window : rolling window for output normalisation
    """
    w = dict(DEFAULT_WEIGHTS)
    if weights:
        w.update(weights)

    total_w = sum(w.get(c, 0.0) for c in feature_df.columns)
    if total_w == 0.0:
        raise ValueError("No feature weights matched available columns")

    alpha = pd.Series(0.0, index=feature_df.index)

    for col in feature_df.columns:
        wt = w.get(col, 0.0)
        if wt == 0.0:
            continue

        raw  = feature_df[col].fillna(0.0)
        rstd = raw.rolling(200, min_periods=50).std()
        z    = (raw / rstd.replace(0.0, np.nan)).fillna(0.0).clip(-clip_z, clip_z)
        alpha += (wt / total_w) * z

    # Final z-score normalisation
    rstd  = alpha.rolling(norm_window, min_periods=50).std()
    alpha = (alpha / rstd.replace(0.0, np.nan)).fillna(0.0)

    return alpha.rename("composite_alpha")
